export namespace PlanAction {
  export enum TypeTache {
    LIEN = 'LIEN',
    NAVIGATION = 'NAVIGATION',
    CONSEIL = 'CONSEIL'
  }

  export enum Destination {
    OFFRES_ALTERNANCE = 'OFFRES_ALTERNANCE',
    OFFRES_SERVICE_CIVIQUE = 'OFFRES_SERVICE_CIVIQUE',
    OFFRES_EMPLOI = 'OFFRES_EMPLOI',
    ALLER_VERS = 'ALLER_VERS',
    EVENEMENTS = 'EVENEMENTS'
  }

  export enum Besoin {
    ORIENTER = 'ORIENTER',
    DECOUVRIR_METIERS = 'DECOUVRIR_METIERS',
    FORMER = 'FORMER',
    STAGE_IMMERSION = 'STAGE_IMMERSION',
    ALTERNANCE = 'ALTERNANCE',
    EMPLOI = 'EMPLOI',
    ENGAGER = 'ENGAGER',
    MOBILITE_INTERNATIONALE = 'MOBILITE_INTERNATIONALE',
    ACCOMPAGNE = 'ACCOMPAGNE',
    CREER_ACTIVITE = 'CREER_ACTIVITE',
    VIE_QUOTIDIENNE = 'VIE_QUOTIDIENNE'
  }

  export enum Contrainte {
    PAS_DE_PERMIS = 'PAS_DE_PERMIS',
    PAS_DE_TRANSPORT = 'PAS_DE_TRANSPORT',
    PAS_DE_LOGEMENT = 'PAS_DE_LOGEMENT',
    MANQUE_CONFIANCE = 'MANQUE_CONFIANCE',
    FIN_DE_MOIS = 'FIN_DE_MOIS',
    HANDICAP = 'HANDICAP',
    SANTE = 'SANTE',
    GARDE_ENFANT = 'GARDE_ENFANT',
    NUMERIQUE = 'NUMERIQUE',
    PAS_DE_DIPLOME = 'PAS_DE_DIPLOME',
    PEU_EXPERIENCE = 'PEU_EXPERIENCE',
    FRANCAIS = 'FRANCAIS'
  }
}
