name: PR Continuous Integration - API

on:
  push:
    branches: [ develop, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.8
    env:
      SQLALCHEMY_DATABASE_TEST_URI: postgresql://test:test@postgres/test
      ENV: test
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          python -m pytest tests/
